---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```



```{r}
data <- read_csv("~/Downloads/TCS_PUBLIC_ALL_02-28-2025.csv")

df_filtered <- data %>%
  filter(institution == "UT Austin")


  filter(str_detect(Employee, "Assistant Professor$"))
  
  
df_filtered %>% View()
```


```{r}
df_filtered %>%
  filter(str_detect(full_name, "Gloria"))
```


```{r}
target_names <- c(
  "Ari Adut",
  "Javier Auyero",
  "Casey Breen",
  "Shannon Cavanagh",
  "Mounira Charrad",
  "Jacob Cheadle",
  "Diane Coffey",
  "Jordan Conwell",
  "Dagoberto Cortez",
  "Robert Crosnoe",
  "Christy Erving",
  "Daniel Fridman",
  "Jennifer Glass",
  "Gloria Gonzalez-Lopez",
  "Bridget Goosby",
  "Kathleen Griesbach",
  "Chantal Hailey",
  "Mark Hayward",
  "Ken-Hou Lin",
  "Chandra Muller",
  "Marc Musick",
  "Pamela Paxton",
  "Kim Pernell",
  "Becky Pettit",
  "Daniel Powers",
  "Blanca Ramirez",
  "Robert Reece",
  "Mark Regnerus",
  "Nestor Rodriguez",
  "Mary Rose",
  "Harel Shapira",
  "Michael Sierra-Arévalo",
  "Debra Umberson",
  "Abigail Weitzman",
  "Christine Williams",
  "Michael Young"
)
```



```{r}
library(stringr)

df_filtered %>%
  filter(full_name %in% target_names) %>% 
  View()
```


```{r}
  <- df_filtered %>%
  filter(full_name %in% target_names)
```



```{r}
df_new %>% 
  ggplot(aes(x = salary_dollars)) + 
  geom_histogram(fill = "grey", color = "black") + 
  scale_x_continuous(labels = scales::label_dollar(), limits = c(0, NA)) + 
  theme_cowplot() + 
  geom_vline(xintercept = 110000, color = "red", size = 1, linetype = "dashed") + 
  annotate("text", x = 150000, y = 8.8, label = "Casey Salary", color = "red")

```



```{r}
df_filtered %>% 
  mutate(Salary = parse_number(Salary)) %>% 
  ggplot() + 
  geom_histogram(aes(x = Salary))


df_filtered %>% 
  mutate(Salary = parse_number(Salary)) %>% 
  summarize(mean(Salary), median(Salary))

df_filtered %>% 
  mutate(Salary = parse_number(Salary)) %>% 
  summarize(mean(Salary), median(Salary))


df_filtered %>% 
  mutate(Salary = parse_number(Salary)) %>% 
  summarize(mean(Salary > 110000))
```

