---
title: "Age heaping analysis"
author: Casey Breen
---

Summary: calculate heaping indicators

```{r}
## Library packages 
library(here)
source(here("code", "helpers.R"))

## Read in dmf 
dmf <- fread(here("data", "censoc_dmf_clean.csv"))
```

## Heaping on birth year 

```{r}
## tabulated birth year 
tabulated_byear <- dmf %>% 
  filter(byear %in% c(1890:1915)) %>% 
  group_by(race) %>% 
  count(byear)

## create_plot
heaping_birth_year_plot <- tabulated_byear %>% 
  filter(!is.na(race)) %>% 
  mutate(fill_color = case_when(
    byear %in% seq(1885, 1920, by = 5) ~ "grey47",   # heaped years
    byear == 1884 ~ "white",
    TRUE ~ "white"
  )) %>% 
  ggplot(aes(x = byear, y = n, fill = fill_color)) + 
  geom_col(color = "black") +
  scale_fill_identity() +
  scale_y_continuous(label = scales::comma) +
  cowplot::theme_cowplot() +
  facet_wrap(~race, ncol = 2, scales = "free") +
  labs(x = "Birth Year (DMF)", 
       y = "Count") +
  theme(
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold", color = "black"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9", color = NA),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    legend.position = "NULL",
    legend.justification = "center",  # centers the whole legend box
    legend.title = element_text(size = 13, hjust = 0.5, vjust = 1, margin = margin(b = 4)),
    legend.text = element_text(size = 11),
    axis.title.x = element_text(face = "bold")
  ) 
```

## Heaping on birth year 

```{r}
## Tabulate census age 
tabulated_census_age <- dmf %>% 
  filter(byear %in% c(1890:1905)) %>% 
  group_by(race) %>% 
  count(census_age)

## Create plot 
heaping_census_age_plot <- tabulated_census_age %>% 
  filter(!is.na(race)) %>% 
  mutate(fill_color = case_when(
    census_age %in% seq(20, 55, by = 5) ~ "grey47",   # heaped ages
    TRUE ~ "white"                                   # everything else white
  )) %>% 
  ggplot(aes(x = census_age, y = n, fill = fill_color)) +
  geom_col(color = "black") +
  scale_fill_identity() +
  scale_y_continuous(label = scales::comma) +
  cowplot::theme_cowplot() +
  facet_wrap(~race, ncol = 2, scales = "free") +
  labs(
    x = "Age (1940 Census)",
    y = "Count"
  ) +
  theme(
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9"),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    legend.position = "none",
    axis.title.x = element_text(face = "bold")
  )
```


```{r}
## Tabulate death year 
tabulated_dyear <- dmf %>% 
  filter(dyear %in% c(1975:2005)) %>% 
  group_by(race) %>% 
  count(dyear)

## Create plot 
heaping_death_year_plot <- tabulated_dyear %>% 
  filter(!is.na(race)) %>% 
  mutate(fill_color = case_when(
    dyear %in% seq(1975, 2005, by = 5) ~ "grey47",  # emphasized years
    TRUE ~ "white"                                 # all others
  )) %>% 
  ggplot(aes(x = dyear, y = n, fill = fill_color)) + 
  geom_col(color = "black") + 
  scale_fill_identity() +
  scale_y_continuous(label = scales::comma) + 
  cowplot::theme_cowplot() + 
  facet_wrap(~race, ncol = 2, scales = "free") + 
  labs(
    x = "Death Year (DMF)",
    y = "Count"
  ) + 
  theme(
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold", color = "black"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9", color = NA),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    legend.position = "none",
    legend.justification = "center",
    legend.title = element_text(size = 13, hjust = 0.5, vjust = 1, margin = margin(b = 4)),
    legend.text = element_text(size = 11),
    axis.title.x = element_text(face = "bold")
  )
```


```{r}
## Age heaping figures 
heaping_combined_plot <- cowplot::plot_grid(
  heaping_birth_year_plot,
  NULL,
  heaping_death_year_plot,
  NULL,
  heaping_census_age_plot,
  nrow = 5,
  rel_heights = c(1, 0.2, 1, 0.2, 1),
  labels = c("A", "", "B", "", "C")
)

## Plot death year 
ggsave(plot = heaping_combined_plot, filename = here("figures", "fig3_age_heaping_plot.png"), width = 8, height = 10, bg = "white")
```

