---
title: "censoc"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
library(haven)
```



```{r}

fat22 <- read_dta("~/Downloads/h22e3a_STATA/h22e3a.dta")
rand  <- read_dta("~/Downloads/randhrs1992_2022v1_STATA/randhrs1992_2022v1.dta")
```

```{r}
data <- fat22 %>%
  left_join(rand, by = c("hhid","pn"))

data$radyear
```



```{r}
data <- data %>%
  mutate(
    death = !is.na(radage_y),
    age_death = radage_y
  )
```


```{r}
data <- data %>%
  mutate(
    age_end = ifelse(!is.na(radage_y), radage_y, 2022 - rabyear)
  )
```


```{r}
data <- rand %>%
  transmute(
    race = raracem,
    birth_year = rabyear,
    death_year = radyear
  ) %>%
  mutate(
    age_death = death_year - birth_year,
    age_end = ifelse(!is.na(age_death), age_death, 2022 - birth_year)
  )


```



```{r}
ages <- 50:100

mortality <- lapply(ages, function(a) {

  exposure <- data %>%
    filter(age_end >= a)

  exposure %>%
    group_by(race) %>%
    summarise(
      age = a,
      exposure = n(),
      deaths = sum(age_death == a, na.rm = TRUE),
      mx = deaths / exposure,
      .groups = "drop"
    )

}) %>% bind_rows()
```



```{r}
mortality5 <- mortality %>%
  mutate(age5 = floor(age/5) * 5) %>%
  group_by(age5, race) %>%
  summarise(
    deaths = sum(deaths),
    exposure = sum(exposure),
    mx = deaths / exposure,
    .groups = "drop"
  ) 

ggplot(
  mortality %>% filter(race %in% c(1,2)),
  aes(age, mx, color = factor(race))
) +
  geom_line() +
  scale_y_log10() +
  labs(color = "Race") + 
  cowplot::theme_cowplot()
```


```{r}
library(dplyr)

data_smoke <- rand %>%
  transmute(
    race = raracem,
    birth_year = rabyear,
    death_year = radyear,
    smoker = r1smoken
  ) %>%
  mutate(
    age_death = death_year - birth_year,
    age_end = ifelse(!is.na(age_death), age_death, 2022 - birth_year)
  ) %>%
  filter(race %in% c(1,2), !is.na(smoker)) %>% 
  filter(birth_year %in% 1920:1930)



survivors <- data_smoke %>%
  rowwise() %>%
  mutate(age = list(50:floor(99))) %>%
  unnest(age) %>%
  ungroup()

ages <- 50:99

smoking_age <- lapply(ages, function(a) {
  data_smoke %>%
    filter(age_end >= a) %>%
    group_by(race) %>%
    summarise(
      age = a,
      smoking_rate = mean(smoker == 1, na.rm = TRUE),
      n = n(),
      .groups = "drop"
    )
}) %>%
  bind_rows()

ggplot(smoking_age,
       aes(age, smoking_rate, color = factor(race))) +
  geom_line(linewidth = 1) +
  labs(
    y = "Smoking prevalence among survivors",
    x = "Age",
    color = "Race"
  )

```

```{r}
coxph(
  Surv(50, age_end, !is.na(death_year)) ~ smoker + factor(race),
  data = data_smoke
)
```


